os: Visual Studio 2015

# Version format
version: 0.1.0.{build}

cache:
  - src\packages -> **\packages.config   # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified

branches:
  only:
    - develop
    - master

# UMBRACO_PACKAGE_PRERELEASE_SUFFIX if a rtm release build this should be blank, otherwise if empty will default to alpha
# example UMBRACO_PACKAGE_PRERELEASE_SUFFIX=beta
init:
  - set UMBRACO_PACKAGE_PRERELEASE_SUFFIX=beta

build_script:
- build-appveyor.cmd

artifacts:
  - path: artifacts\*.nupkg
  - path: artifacts\*.zip

deploy:
    # GitHub Deployment for releases
  - provider: GitHub
    auth_token:
      secure: hCVdUevee3V4EaB55b2luIbZ6Myzy6hBh5HQ1po59alyNyt1kWdSE5zrxELKlY6P
    artifact: /.*\.zip/            # upload all Zip packages to release assets
    draft: false
    prerelease: false
    on:
      branch: master
      appveyor_repo_tag: true        # deploy on tag push only

    # NuGet Deployment for releases
  - provider: NuGet
    server:
    api_key:
      secure: SoL/7Q7aYT+ryaPcPoRNTY6Xzn8nRIyu5Ez7S4PHxocwGz5gxHIFzPtG9jtzTd00
    artifact: /.*\.nupkg/
    on:
      branch: master
      appveyor_repo_tag: true